print("Ok, here's my understanding of the change.")
print("The user wants me to 'Implement a standard ServerResponse wrapper for all rpc.ts (remote calls made from the frontend) that includes a success boolean and a localized error message to be displayed in the Svelte UI'.")
print("I will modify:")
print("1. `src/common/types.ts` to update `ServerResponse<T = undefined> = { success: boolean; message?: string; error?: string; data?: T; }`")
print("2. `src/server/importer/rpc.ts`: update `importCSV` and `generatePreview` to return `ServerResponse<any>` and catch errors.")
print("3. `src/server/accounts/rpc.ts`: update `getBankAccounts`, `getBankAccountOptions`, `getBankAccountOptionsCached` to return `ServerResponse<any>` and catch errors.")
print("4. `src/client/components/ImportForm.svelte`: update to handle `ServerResponse<T>` correctly (check `success`, display error if `!success`, get data from `response.data`).")
print("5. `src/client/components/PreviewTable.svelte`: update to handle `ServerResponse<any>`.")
print("6. `src/client/utils/__mocks__/serverFunctions.ts`: update mock responses to use `ServerResponse`.")
print("What about other `rpc.ts` functions? `mailNetWorth`, `executeFindDuplicates`, `executeAutomaticCategorization`, `debugImportSettings` - these are triggered by GAS custom menu, not Svelte frontend. However, the user says 'wrapper for all rpc.ts (remote calls made from the frontend)'. I will wrap the ones explicitly used in the Svelte frontend to not break the GAS UI menus, or I can wrap all of them.")
print("Actually, 'remote calls made from the frontend' refers specifically to the ones called via `serverFunctions` from Svelte.")
