export const PROP_ENABLE_BANKING_APP_ID = 'ENABLE_BANKING_APP_ID'
export const PROP_ENABLE_BANKING_PRIVATE_KEY = 'ENABLE_BANKING_PRIVATE_KEY'
export const PROP_ENABLE_BANKING_CONNECTIONS = 'ENABLE_BANKING_CONNECTIONS'

export const PROP_ENABLE_BANKING_TRIGGER_FREQ_TYPE = 'ENABLE_BANKING_TRIGGER_FREQ_TYPE'
export const PROP_ENABLE_BANKING_TRIGGER_FREQ_VAL = 'ENABLE_BANKING_TRIGGER_FREQ_VAL'

export const ENABLE_BANKING_API_URL = 'https://api.enablebanking.com'

export const REDIRECT_URL = 'https://melledijkstra.github.io/gas-fire/docs/enable-banking.html'
