name: 'Setup Environment'
description: 'Sets up Node.js, pnpm, and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
      with:
        version: 10
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash


