import { CategoryDetectionConfigOld } from './types';

export const categoriesTermsMap: CategoryDetectionConfigOld = {
  'Food & Groceries': [
    /supermercado|supermercados/,
    /supermarkt|supermarket/,
    /albert heijn|jumbo|spar/,
    /lidl|aldi/,
    /glovo|ubereats|uber eats/,
    /mercadona|superdino|lupa|alcampo|carrefour|la despensa|eroski/,
  ],
  Salary: [/adidas espana s.a./],
  'Bars, Restaurants & Clubs': [
    /restaurant|restaurante/,
    /cafe|cafeteria|cafetaría/,
    /faborit/,
    /santa gloria/,
    /planta calle/,
    /\bbar\b/,
    /rio de la plata/,
    /teranga/,
    /telepizza/,
    /tagliatella/,
    /mcdonalds|\bkfc\b|starbucks|burger king|domino's|taco bell|papa john|tim horton/,
  ],
  Income: [],
  'Household & Utilities': [
    /iberdrola/,
    /hergar rio sl/,
    /canal de isabel/,
    /ikea/,
    /\bdigi\b/,
  ],
  Debt: [],
  Subscriptions: [/spotify/, /openai/],
  Education: [],
  'Leisure & Entertainment': [/climbing/],
  'Personal Care': [
    /\bbarber|kapper|kapsalon|peluqueria|peluquería|peluqueros/,
    /basicfit|basic-fit/,
    /\bzara|pull&bear|pull and bear|\bmango\b|decathlon|superdry|el corte ingles|\bc&a\b|\bbershka\b|zalando/,
    /\badidasnl\b|\badidases\b/,
    /fisionarte/,
  ],
  'Healthcare & Drug Stores': [/pharmacy|apotheek|apotheken|farmacia/],
  'Insurances & Finances': [],
  'Family, Friends & Donations': [],
  'Media & Electronics': [/media markt/, /google/],
  'Transport & Car': [/aparcamientos|parking/],
  'Travel & Holidays': [],
  'Savings & Investments': [/\bdegiro\b/],
  'Business expenses': [],
  Miscellaneous: [],
};
