name: CI Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Environment
        uses: ./.github/actions/setup-env
      - name: Lint code
        run: pnpm lint
      - name: Build application
        run: pnpm build
      - name: Build documentation
        run: pnpm docs:build
      - name: Run tests with coverage
        run: pnpm test:coverage
