name: CI Pipeline

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env
      - name: Run linting
        run: pnpm lint
      - name: Run build
        run: pnpm build
      - name: Run unit tests
        run: pnpm test:coverage
